import { NgModule } from '@angular/core'

import {
  TuiAccordionModule,
  TuiBadgeModule,
  TuiComboBoxModule,
  TuiDataListWrapperModule,
  TuiIslandModule,
  TuiTabsModule,
  TuiTagModule,
  TuiSelectModule,
  TuiInputModule,
  TuiInputNumberModule,
  TuiFilterModule,
  TuiMultiSelectModule,
  TuiToggleModule,
  TuiRadioBlockModule,
  TuiRadioLabeledModule,
  TuiCheckboxLabeledModule,
  TuiProgressModule,
  TuiInputFilesModule,
  TuiCheckboxModule,
  TuiRatingModule,
  TuiBadgedContentModule,
  TuiAvatarModule,
  TuiCarouselModule,
  TuiInputSliderModule,
  TuiStringifyPipeModule,
  TuiFilterByInputPipeModule,
  TuiStringifyContentPipeModule,
} from '@taiga-ui/kit'
import {
  TuiDialogModule,
  TuiSvgModule,
  TuiThemeNightModule,
  TuiModeModule,
  TuiHostedDropdownModule,
  TuiDataListModule,
  TuiButtonModule,
  TuiLabelModule,
  TuiLoaderModule,
  TuiTextfieldControllerModule,
  TuiGroupModule,
  TuiHintModule,
  TuiPrimitiveCheckboxModule,
  TuiPrimitiveTextfieldModule,
  TuiTooltipModule,
  TuiExpandModule,
  TuiScrollbarModule,
  TuiDropdownModule,
} from '@taiga-ui/core'

import { TuiLetModule, TuiFilterPipeModule } from '@taiga-ui/cdk'
import { TuiTableModule } from '@taiga-ui/addon-table'
import { PolymorpheusModule } from '@tinkoff/ng-polymorpheus'
import { TuiMapperPipeModule } from '@taiga-ui/cdk'
import { TuiActiveZoneModule } from '@taiga-ui/cdk'
import { TuiTablePaginationModule } from '@taiga-ui/addon-table'
import { TuiHighlightModule } from '@taiga-ui/kit'
import { TuiStepperModule } from '@taiga-ui/kit'
@NgModule({
  exports: [
    TuiDialogModule,
    TuiAccordionModule,
    TuiComboBoxModule,
    TuiBadgeModule,
    TuiButtonModule,
    TuiDataListModule,
    TuiDataListWrapperModule,
    TuiTabsModule,
    TuiSvgModule,
    TuiHostedDropdownModule,
    TuiTagModule,
    TuiThemeNightModule,
    TuiModeModule,
    TuiIslandModule,
    TuiLabelModule,
    TuiLoaderModule,
    TuiSelectModule,
    TuiTextfieldControllerModule,
    TuiInputModule,
    TuiInputNumberModule,
    TuiGroupModule,
    TuiHintModule,
    TuiFilterModule,
    TuiMultiSelectModule,
    TuiPrimitiveTextfieldModule,
    TuiRadioBlockModule,
    TuiRadioLabeledModule,
    TuiToggleModule,
    TuiTooltipModule,
    TuiHintModule,
    TuiExpandModule,
    TuiScrollbarModule,
    TuiLetModule,
    TuiFilterPipeModule,
    TuiTableModule,
    PolymorpheusModule,
    TuiCheckboxLabeledModule,
    TuiProgressModule,
    TuiInputFilesModule,
    TuiCheckboxModule,
    TuiRatingModule,
    TuiBadgedContentModule,
    TuiPrimitiveCheckboxModule,
    TuiMapperPipeModule,
    TuiDropdownModule,
    TuiActiveZoneModule,
    TuiTablePaginationModule,
    TuiAvatarModule,
    TuiDropdownModule,
    TuiHighlightModule,
    TuiCarouselModule,
    TuiStepperModule,
    TuiInputSliderModule,
    TuiFilterByInputPipeModule,
    TuiStringifyPipeModule,
    TuiStringifyContentPipeModule,
  ],
})
export class TuiModule {}
